export { default as Highcharts } from "highcharts/esm/highcharts.js";

export const loadMore = async () => {
  await import("highcharts/esm/highcharts-more.js");
};

const indicatorLoader = {
  "acceleration-bands": () => import("highcharts/esm/indicators/acceleration-bands.js"),
  "accumulation-distribution": () => import("highcharts/esm/indicators/accumulation-distribution.js"),
  ao: () => import("highcharts/esm/indicators/ao.js"),
  apo: () => import("highcharts/esm/indicators/apo.js"),
  aroon: () => import("highcharts/esm/indicators/aroon.js"),
  "aroon-oscillator": () => import("highcharts/esm/indicators/aroon-oscillator.js"),
  atr: () => import("highcharts/esm/indicators/atr.js"),
  "bollinger-bands": () => import("highcharts/esm/indicators/bollinger-bands.js"),
  cci: () => import("highcharts/esm/indicators/cci.js"),
  chaikin: () => import("highcharts/esm/indicators/chaikin.js"),
  cmf: () => import("highcharts/esm/indicators/cmf.js"),
  cmo: () => import("highcharts/esm/indicators/cmo.js"),
  dema: () => import("highcharts/esm/indicators/dema.js"),
  "disparity-index": () => import("highcharts/esm/indicators/disparity-index.js"),
  dmi: () => import("highcharts/esm/indicators/dmi.js"),
  dpo: () => import("highcharts/esm/indicators/dpo.js"),
  ema: () => import("highcharts/esm/indicators/ema.js"),
  "ichimoku-kinko-hyo": () => import("highcharts/esm/indicators/ichimoku-kinko-hyo.js"),
  indicators: () => import("highcharts/esm/indicators/indicators.js"),
  "indicators-all": () => import("highcharts/esm/indicators/indicators-all.js"),
  "keltner-channels": () => import("highcharts/esm/indicators/keltner-channels.js"),
  klinger: () => import("highcharts/esm/indicators/klinger.js"),
  macd: () => import("highcharts/esm/indicators/macd.js"),
  mfi: () => import("highcharts/esm/indicators/mfi.js"),
  momentum: () => import("highcharts/esm/indicators/momentum.js"),
  natr: () => import("highcharts/esm/indicators/natr.js"),
  obv: () => import("highcharts/esm/indicators/obv.js"),
  "pivot-points": () => import("highcharts/esm/indicators/pivot-points.js"),
  ppo: () => import("highcharts/esm/indicators/ppo.js"),
  "price-channel": () => import("highcharts/esm/indicators/price-channel.js"),
  "price-envelopes": () => import("highcharts/esm/indicators/price-envelopes.js"),
  psar: () => import("highcharts/esm/indicators/psar.js"),
  regressions: () => import("highcharts/esm/indicators/regressions.js"),
  roc: () => import("highcharts/esm/indicators/roc.js"),
  rsi: () => import("highcharts/esm/indicators/rsi.js"),
  "slow-stochastic": () => import("highcharts/esm/indicators/slow-stochastic.js"),
  stochastic: () => import("highcharts/esm/indicators/stochastic.js"),
  supertrend: () => import("highcharts/esm/indicators/supertrend.js"),
  tema: () => import("highcharts/esm/indicators/tema.js"),
  trendline: () => import("highcharts/esm/indicators/trendline.js"),
  trix: () => import("highcharts/esm/indicators/trix.js"),
  "volume-by-price": () => import("highcharts/esm/indicators/volume-by-price.js"),
  vwap: () => import("highcharts/esm/indicators/vwap.js"),
  "williams-r": () => import("highcharts/esm/indicators/williams-r.js"),
  wma: () => import("highcharts/esm/indicators/wma.js"),
  zigzag: () => import("highcharts/esm/indicators/zigzag.js"),
};

const moduleLoader = {
  accessibility: () => import("highcharts/esm/modules/accessibility.js"),
  annotations: () => import("highcharts/esm/modules/annotations.js"),
  "annotations-advanced": () => import("highcharts/esm/modules/annotations-advanced.js"),
  "arc-diagram": () => import("highcharts/esm/modules/arc-diagram.js"),
  "arrow-symbols": () => import("highcharts/esm/modules/arrow-symbols.js"),
  boost: () => import("highcharts/esm/modules/boost.js"),
  "boost-canvas": () => import("highcharts/esm/modules/boost-canvas.js"),
  "broken-axis": () => import("highcharts/esm/modules/broken-axis.js"),
  bullet: () => import("highcharts/esm/modules/bullet.js"),
  coloraxis: () => import("highcharts/esm/modules/coloraxis.js"),
  "current-date-indicator": () => import("highcharts/esm/modules/current-date-indicator.js"),
  cylinder: () => import("highcharts/esm/modules/cylinder.js"),
  data: () => import("highcharts/esm/modules/data.js"),
  "data-tools": () => import("highcharts/esm/modules/data-tools.js"),
  datagrouping: () => import("highcharts/esm/modules/datagrouping.js"),
  debugger: () => import("highcharts/esm/modules/debugger.js"),
  "dependency-wheel": () => import("highcharts/esm/modules/dependency-wheel.js"),
  dotplot: () => import("highcharts/esm/modules/dotplot.js"),
  "drag-panes": () => import("highcharts/esm/modules/drag-panes.js"),
  "draggable-points": () => import("highcharts/esm/modules/draggable-points.js"),
  drilldown: () => import("highcharts/esm/modules/drilldown.js"),
  dumbbell: () => import("highcharts/esm/modules/dumbbell.js"),
  "export-data": () => import("highcharts/esm/modules/export-data.js"),
  exporting: () => import("highcharts/esm/modules/exporting.js"),
  flowmap: () => import("highcharts/esm/modules/flowmap.js"),
  "full-screen": () => import("highcharts/esm/modules/full-screen.js"),
  funnel: () => import("highcharts/esm/modules/funnel.js"),
  funnel3d: () => import("highcharts/esm/modules/funnel3d.js"),
  gantt: () => import("highcharts/esm/modules/gantt.js"),
  geoheatmap: () => import("highcharts/esm/modules/geoheatmap.js"),
  "grid-axis": () => import("highcharts/esm/modules/grid-axis.js"),
  heatmap: () => import("highcharts/esm/modules/heatmap.js"),
  heikinashi: () => import("highcharts/esm/modules/heikinashi.js"),
  "histogram-bellcurve": () => import("highcharts/esm/modules/histogram-bellcurve.js"),
  hollowcandlestick: () => import("highcharts/esm/modules/hollowcandlestick.js"),
  "item-series": () => import("highcharts/esm/modules/item-series.js"),
  lollipop: () => import("highcharts/esm/modules/lollipop.js"),
  map: () => import("highcharts/esm/modules/map.js"),
  "marker-clusters": () => import("highcharts/esm/modules/marker-clusters.js"),
  "mouse-wheel-zoom": () => import("highcharts/esm/modules/mouse-wheel-zoom.js"),
  navigator: () => import("highcharts/esm/modules/navigator.js"),
  networkgraph: () => import("highcharts/esm/modules/networkgraph.js"),
  "no-data-to-display": () => import("highcharts/esm/modules/no-data-to-display.js"),
  "non-cartesian-zoom": () => import("highcharts/esm/modules/non-cartesian-zoom.js"),
  "offline-exporting": () => import("highcharts/esm/modules/offline-exporting.js"),
  organization: () => import("highcharts/esm/modules/organization.js"),
  "parallel-coordinates": () => import("highcharts/esm/modules/parallel-coordinates.js"),
  pareto: () => import("highcharts/esm/modules/pareto.js"),
  pathfinder: () => import("highcharts/esm/modules/pathfinder.js"),
  "pattern-fill": () => import("highcharts/esm/modules/pattern-fill.js"),
  pictorial: () => import("highcharts/esm/modules/pictorial.js"),
  pointandfigure: () => import("highcharts/esm/modules/pointandfigure.js"),
  "price-indicator": () => import("highcharts/esm/modules/price-indicator.js"),
  pyramid3d: () => import("highcharts/esm/modules/pyramid3d.js"),
  renko: () => import("highcharts/esm/modules/renko.js"),
  sankey: () => import("highcharts/esm/modules/sankey.js"),
  "series-label": () => import("highcharts/esm/modules/series-label.js"),
  "series-on-point": () => import("highcharts/esm/modules/series-on-point.js"),
  "solid-gauge": () => import("highcharts/esm/modules/solid-gauge.js"),
  sonification: () => import("highcharts/esm/modules/sonification.js"),
  "static-scale": () => import("highcharts/esm/modules/static-scale.js"),
  stock: () => import("highcharts/esm/modules/stock.js"),
  "stock-tools": () => import("highcharts/esm/modules/stock-tools.js"),
  streamgraph: () => import("highcharts/esm/modules/streamgraph.js"),
  sunburst: () => import("highcharts/esm/modules/sunburst.js"),
  textpath: () => import("highcharts/esm/modules/textpath.js"),
  tiledwebmap: () => import("highcharts/esm/modules/tiledwebmap.js"),
  tilemap: () => import("highcharts/esm/modules/tilemap.js"),
  timeline: () => import("highcharts/esm/modules/timeline.js"),
  treegraph: () => import("highcharts/esm/modules/treegraph.js"),
  treegrid: () => import("highcharts/esm/modules/treegrid.js"),
  treemap: () => import("highcharts/esm/modules/treemap.js"),
  "variable-pie": () => import("highcharts/esm/modules/variable-pie.js"),
  variwide: () => import("highcharts/esm/modules/variwide.js"),
  vector: () => import("highcharts/esm/modules/vector.js"),
  venn: () => import("highcharts/esm/modules/venn.js"),
  windbarb: () => import("highcharts/esm/modules/windbarb.js"),
  wordcloud: () => import("highcharts/esm/modules/wordcloud.js"),
  xrange: () => import("highcharts/esm/modules/xrange.js"),
};

const extraDependencies = {
  "aroon-oscillator": ["aroon"],
  flowmap: ["map"],
  geoheatmap: ["map"],
  "keltner-channels": ["atr"],
  lollipop: ["dumbbell"],
  natr: ["atr"],
  "slow-stochastic": ["stochastic"],
  tiledwebmap: ["map"],
  trix: ["tema"],
};

// Indicators build on the "indicators" base module, and a few modules build on another module.
const dependenciesOf = (moduleName) => [
  ...(Object.hasOwn(indicatorLoader, moduleName) && moduleName !== "indicators" ? ["indicators"] : []),
  ...(extraDependencies[moduleName] ?? []),
];

export const loadModule = async (moduleName) => {
  for (const dependency of dependenciesOf(moduleName)) {
    await loadModule(dependency);
  }
  await (indicatorLoader[moduleName] ?? moduleLoader[moduleName])();
};
