export { default as Highcharts } from "highcharts";

export const loadMore = async () => {
  await import("highcharts/highcharts-more");
};

export const loadModule = async (moduleName) => {
  await {
    accessibility: () => import("highcharts/modules/accessibility"),
    annotations: () => import("highcharts/modules/annotations"),
    "annotations-advanced": () => import("highcharts/modules/annotations"),
    "arc-diagram": () => import("highcharts/modules/arc"),
    "arrow-symbols": () => import("highcharts/modules/arrow"),
    boost: () => import("highcharts/modules/boost"),
    "boost-canvas": () => import("highcharts/modules/boost"),
    "broken-axis": () => import("highcharts/modules/broken"),
    bullet: () => import("highcharts/modules/bullet"),
    coloraxis: () => import("highcharts/modules/coloraxis"),
    "current-date-indicator": () => import("highcharts/modules/current"),
    cylinder: () => import("highcharts/modules/cylinder"),
    data: () => import("highcharts/modules/data"),
    "data-tools.js": () => import("highcharts/modules/data"),
    "data-tools": () => import("highcharts/modules/data"),
    datagrouping: () => import("highcharts/modules/datagrouping"),
    debugger: () => import("highcharts/modules/debugger"),
    "dependency-wheel": () => import("highcharts/modules/dependency"),
    dotplot: () => import("highcharts/modules/dotplot"),
    "drag-panes": () => import("highcharts/modules/drag"),
    "draggable-points": () => import("highcharts/modules/draggable"),
    drilldown: () => import("highcharts/modules/drilldown"),
    dumbbell: () => import("highcharts/modules/dumbbell"),
    "export-data": () => import("highcharts/modules/export"),
    exporting: () => import("highcharts/modules/exporting"),
    flowmap: () => import("highcharts/modules/flowmap"),
    "full-screen": () => import("highcharts/modules/full"),
    funnel: () => import("highcharts/modules/funnel"),
    funnel3d: () => import("highcharts/modules/funnel3d"),
    gantt: () => import("highcharts/modules/gantt"),
    geoheatmap: () => import("highcharts/modules/geoheatmap"),
    "grid-axis": () => import("highcharts/modules/grid"),
    heatmap: () => import("highcharts/modules/heatmap"),
    heikinashi: () => import("highcharts/modules/heikinashi"),
    "histogram-bellcurve": () => import("highcharts/modules/histogram"),
    hollowcandlestick: () => import("highcharts/modules/hollowcandlestick"),
    "item-series": () => import("highcharts/modules/item"),
    lollipop: () => import("highcharts/modules/lollipop"),
    map: () => import("highcharts/modules/map"),
    "marker-clusters": () => import("highcharts/modules/marker"),
    "mouse-wheel-zoom": () => import("highcharts/modules/mouse"),
    navigator: () => import("highcharts/modules/navigator"),
    networkgraph: () => import("highcharts/modules/networkgraph"),
    "no-data-to-display": () => import("highcharts/modules/no"),
    "non-cartesian-zoom": () => import("highcharts/modules/non"),
    "offline-exporting": () => import("highcharts/modules/offline"),
    organization: () => import("highcharts/modules/organization"),
    "parallel-coordinates": () => import("highcharts/modules/parallel"),
    pareto: () => import("highcharts/modules/pareto"),
    pathfinder: () => import("highcharts/modules/pathfinder"),
    "pattern-fill": () => import("highcharts/modules/pattern"),
    pictorial: () => import("highcharts/modules/pictorial"),
    pointandfigure: () => import("highcharts/modules/pointandfigure"),
    "price-indicator": () => import("highcharts/modules/price"),
    pyramid3d: () => import("highcharts/modules/pyramid3d"),
    renko: () => import("highcharts/modules/renko"),
    sankey: () => import("highcharts/modules/sankey"),
    "series-label": () => import("highcharts/modules/series"),
    "series-on-point": () => import("highcharts/modules/series"),
    "solid-gauge": () => import("highcharts/modules/solid"),
    sonification: () => import("highcharts/modules/sonification"),
    "static-scale": () => import("highcharts/modules/static"),
    stock: () => import("highcharts/modules/stock"),
    "stock-tools": () => import("highcharts/modules/stock"),
    streamgraph: () => import("highcharts/modules/streamgraph"),
    sunburst: () => import("highcharts/modules/sunburst"),
    textpath: () => import("highcharts/modules/textpath"),
    tiledwebmap: () => import("highcharts/modules/tiledwebmap"),
    tilemap: () => import("highcharts/modules/tilemap"),
    timeline: () => import("highcharts/modules/timeline"),
    treegraph: () => import("highcharts/modules/treegraph"),
    treegrid: () => import("highcharts/modules/treegrid"),
    treemap: () => import("highcharts/modules/treemap"),
    "variable-pie": () => import("highcharts/modules/variable"),
    variwide: () => import("highcharts/modules/variwide"),
    vector: () => import("highcharts/modules/vector"),
    venn: () => import("highcharts/modules/venn"),
    windbarb: () => import("highcharts/modules/windbarb"),
    wordcloud: () => import("highcharts/modules/wordcloud"),
    xrange: () => import("highcharts/modules/xrange"),
  }[moduleName]();
};
